export const PAYSTACK_PROVIDER = Symbol("PAYSTACK_PROVIDER");
export const FLUTTERWAVE_PROVIDER = Symbol("FLUTTERWAVE_PROVIDER");
export const STRIPE_PROVIDER = Symbol("STRIPE_PROVIDER");
export const PAYPAL_PROVIDER = Symbol("PAYPAL_PROVIDER");
